name: Testes em mais de uma versao do node

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x', '18.x']
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Usando Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Instalar dependências
        run: npm install
        
      - name: Executar testes
        run: npm test
